### ISSUE TITLE
When connecting to an EMR using a key file fails, RED-I does not give an informative error report

### ISSUE THREAD

**Issue by nrejack** [ctsit/redi#104]
When connecting to an EMR using a key file, if the EMR key specified in settings.ini is not found RED-I quits without an informative error. The error is clearly seen when running manually but not when automated.

Error should be reported in the log.

**Comment by nrejack** [comment]
Error message seen when running manually (Not present in log when ran non-interactively, i.e., out of cron):

2015-02-19 13:21:40,852 - INFO - redi.utils.redcapClient - redcap interface initialzed
Traceback (most recent call last):
  File "/Users/nrejack/code/redi/v/bin/redi", line 9, in <module>
    load_entry_point('redi-py==0.13.2', 'console_scripts', 'redi')()
  File "build/bdist.macosx-10.10-x86_64/egg/redi/redi.py", line 180, in main
  File "build/bdist.macosx-10.10-x86_64/egg/redi/redi.py", line 281, in _run
  File "build/bdist.macosx-10.10-x86_64/egg/redi/utils/GetEmrData.py", line 133, in get_emr_data
  File "build/bdist.macosx-10.10-x86_64/egg/redi/utils/GetEmrData.py", line 56, in download_file
  File "build/bdist.macosx-10.10-x86_64/egg/pysftp.py", line 150, in __init__
  File "build/bdist.macosx-10.10-x86_64/egg/paramiko/transport.py", line 224, in __init__
paramiko.ssh_exception.SSHException: Unable to connect to server.server.address: [Errno 61] Connection refused

**Comment by nrejack** [comment]
In settings.ini, the following must be set:
 emr_sftp_server_username = username
emr_sftp_server_private_key = /path/to/key/file

and the following must be unset:
emr_sftp_server_password =
emr_sftp_server_private_key_pass =
